package com.butchercraft.world.evidence;

public enum EvidenceLifecycleFailureCode {
    MISSING_OWNER,
    INVALID_IDENTITY,
    CONTRADICTORY_CLASSIFICATION,
    UNSUPPORTED_POLICY_VERSION,
    RETENTION_REQUEST_VIOLATES_REPLAY_GUARANTEE,
    RETENTION_DISCARDS_AUTHORITATIVE_EVIDENCE,
    RETENTION_DISCARDS_PERMANENT_AUDIT_EVIDENCE,
    IDENTITY_CONTENT_CONFLICT,
    REQUIRED_GUARANTEE_MISSING,
    INVALID_POLICY_INPUT
}
