package com.butchercraft.world.evidence;

public enum EvidenceRetentionReason {
    AUTHORITATIVE_FACT_PROTECTED,
    PERMANENT_AUDIT_PROTECTED,
    WITHIN_REPLAY_HORIZON,
    OUTSIDE_REPLAY_HORIZON,
    ARCHIVE_PUBLICATION_AVAILABLE,
    DERIVED_SUMMARY_REBUILDABLE,
    SOURCE_EVIDENCE_RETAINED,
    DIAGNOSTIC_EXPIRY_EXPLICITLY_ENABLED,
    DIAGNOSTIC_EXPIRY_NOT_ENABLED,
    DIAGNOSTIC_STILL_INSIDE_POLICY_WINDOW,
    CAPACITY_PRESSURE_PRESENT,
    POLICY_RETAINS_HOT,
    UNSUPPORTED_POLICY_VERSION,
    MISSING_REQUIRED_GUARANTEE
}
