package com.butchercraft.world.evidence;

public enum EvidenceLifecycleDisposition {
    RETAIN_HOT,
    ELIGIBLE_FOR_ARCHIVE,
    RETAINED_IN_COLD_ARCHIVE,
    ELIGIBLE_FOR_DERIVED_DATA_REBUILD,
    ELIGIBLE_FOR_DETERMINISTIC_DIAGNOSTIC_EXPIRY,
    PROTECTED_FROM_DELETION,
    LIFECYCLE_BLOCKED_BY_MISSING_GUARANTEES
}
