package com.butchercraft.world.economy.order;

public enum ContractFailureCode {
    DUPLICATE_CONTRACT_ID, UNKNOWN_CONTRACT, UNKNOWN_ACTOR, INVALID_PARTIES, UNKNOWN_GOOD,
    UNIT_MISMATCH, INVALID_QUANTITY, INVALID_TERM, INVALID_SCHEDULE, INVALID_TICK_RANGE,
    DUPLICATE_LINE_ID, INVALID_STATUS, INVALID_STATUS_TRANSITION, TERMINAL_CONTRACT,
    UNKNOWN_ORDER_REFERENCE, CONTRACT_ORDER_MISMATCH, UNSUPPORTED_OPERATION, VALIDATION_FAILED, UNKNOWN
}
