package com.butchercraft.world.economy.order;

public enum OrderFailureCode {
    DUPLICATE_ORDER_ID, UNKNOWN_ORDER, UNKNOWN_ORDER_LINE, UNKNOWN_ACTOR, INVALID_PARTIES,
    UNKNOWN_GOOD, UNIT_MISMATCH, INVALID_QUANTITY, EMPTY_ORDER, DUPLICATE_LINE_ID,
    INVALID_TICK_RANGE, INVALID_STATUS, INVALID_STATUS_TRANSITION, UNKNOWN_CONTRACT,
    CONTRACT_NOT_ACTIVE, CONTRACT_SCOPE_MISMATCH, UNKNOWN_TRANSACTION, TRANSACTION_NOT_APPLIED,
    TRANSACTION_GOOD_MISMATCH, TRANSACTION_QUANTITY_EXCEEDED, DUPLICATE_TRANSACTION_ALLOCATION,
    OVER_FULFILLMENT, TERMINAL_ORDER, UNSUPPORTED_OPERATION, VALIDATION_FAILED, UNKNOWN
}
