package com.butchercraft.world.checkpoint;

public enum CheckpointRecoveryOutcome {
    LATEST_VALID_GENERATION_SELECTED,
    OLDER_VALID_GENERATION_SELECTED_AUTOMATICALLY,
    EXPLICIT_ROLLBACK_TARGET_ACCEPTED,
    RECOVERY_BLOCKED,
    INVALID_ROLLBACK_REQUEST,
    INTEGRITY_FAILURE,
    UNSUPPORTED_SCHEMA,
    WORLD_IDENTITY_MISMATCH,
    PLATFORM_DETERMINISM_MANIFEST_MISMATCH
}
