package com.butchercraft.world.checkpoint;

public enum LegacySplitRecoveryPublicationPhase {
    BEFORE_AUTHORIZATION_VALIDATION,
    AFTER_REANALYSIS_BEFORE_OWNER_PREPARATION,
    AFTER_SOME_OWNER_PREPARATIONS,
    AFTER_ALL_OWNER_PREPARATIONS,
    AFTER_GENERATION_METADATA_PUBLICATION,
    BEFORE_INACTIVE_HEAD_UPDATE,
    DURING_INACTIVE_HEAD_UPDATE,
    AFTER_COMMITTED_HEAD_BEFORE_RESULT_OBSERVATION
}
