package com.butchercraft.world.checkpoint;

public enum StartupRecoveryFailureCode {
    LIVE_SPLIT_SNAPSHOT,
    NO_VALID_CHECKPOINT,
    CHECKPOINT_INVALID,
    CHECKPOINT_NOT_RESTORABLE,
    WORKSTATION_PROJECTION_INCOMPLETE,
    OWNER_SCHEMA_UNSUPPORTED,
    WORLD_IDENTITY_MISMATCH,
    CONFIGURATION_MISMATCH,
    RESTORATION_INCOMPLETE,
    RESTORATION_CONFLICT,
    RESTORATION_EVIDENCE_INVALID,
    AUTHORITY_BLOCK,
    UNKNOWN_OUTCOME
}
