package com.butchercraft.development.checkpoint;

public enum DevelopmentCheckpointFailureCode {
    NOT_IN_DEVELOPMENT_ENVIRONMENT,
    NO_ACTIVE_WORLD,
    CHECKPOINT_OPERATION_ALREADY_ACTIVE,
    CHECKPOINT_ROOT_UNAVAILABLE,
    MISSING_CLOCK_SERVICE,
    MISSING_SCHEDULER_SERVICE,
    MISSING_WORLD_IDENTITY,
    OWNER_CAPTURE_FAILURE,
    PUBLICATION_FAILURE,
    INVALID_GENERATION_SELECTOR,
    GENERATION_NOT_FOUND,
    INTEGRITY_FAILURE,
    WORLD_IDENTITY_MISMATCH,
    PLATFORM_DETERMINISM_MANIFEST_MISMATCH,
    UNSAFE_RESTORATION_BOUNDARY,
    OWNER_PREPARATION_FAILURE,
    OWNER_PUBLICATION_FAILURE,
    ROLLBACK_FAILURE,
    RECOVERY_BLOCKED_STATE
}
