package com.butchercraft.world.manufacturer;

import com.butchercraft.world.identity.BuiltInRegionCatalog;
import com.butchercraft.world.identity.RegionCatalog;

import java.util.EnumSet;
import java.util.List;
import java.util.Set;

public final class BuiltInManufacturerCatalog {
    public static final int MANUFACTURER_COUNT = 30;

    private BuiltInManufacturerCatalog() {
    }

    public static ManufacturerRegistry createRegistry() {
        return ManufacturerRegistry.of(manufacturers(), RegionCatalog.builtIn());
    }

    public static List<Manufacturer> manufacturers() {
        return List.of(
                manufacturer(
                        "prairie_forge_works",
                        "Prairie Forge Works",
                        1912,
                        BuiltInRegionCatalog.PRAIRIE_COMMONWEALTH,
                        "Market Junction",
                        EnumSet.of(ManufacturerCategory.PROCESSING_EQUIPMENT, ManufacturerCategory.SPECIALTY_EQUIPMENT),
                        ManufacturerTier.REGIONAL,
                        EngineeringPhilosophy.BUILT_TO_LAST,
                        "Prairie Forge Works began as a farm repair shop that rebuilt grinders and saw tables for county lockers after hard winters. Its equipment is still designed around thick frames, ordinary hand tools, and parts a rural mechanic can understand.",
                        "Built heavy, kept honest.",
                        branding("#6B2F1A", "#D0B46E", "#2F4A3A", "Cast-iron nameplates, wheat-gold pinstripes, and plain shop-floor lettering"),
                        "heavy grinders",
                        "manual fabrication tables",
                        "rebuild-friendly processing frames",
                        "Known for rugged machines that are rarely fashionable and almost never retired.",
                        "https://manufacturers.invalid/prairie-forge-works",
                        "Durable processing equipment for shops that expect decades of service."
                ),
                manufacturer(
                        "sunfield_value_mechanics",
                        "Sunfield Value Mechanics",
                        1968,
                        BuiltInRegionCatalog.PRAIRIE_COMMONWEALTH,
                        "Sunfield",
                        EnumSet.of(ManufacturerCategory.PROCESSING_EQUIPMENT, ManufacturerCategory.SMALLWARES),
                        ManufacturerTier.REGIONAL,
                        EngineeringPhilosophy.BUDGET_VALUE,
                        "Sunfield Value Mechanics grew from a cooperative buying office that wanted dependable entry-level equipment for small rural shops. It became respected by refusing unnecessary trim and building machines that survive first-business budgets.",
                        "Every shop deserves a sturdy start.",
                        branding("#F2C14E", "#2C5E3F", "#7A3E2C", "Green service panels, yellow safety badges, and clear stamped model numbers"),
                        "entry grinders",
                        "basic trim tables",
                        "starter shop smallwares",
                        "Favored by new operators who need dependable equipment without premium prices.",
                        "https://manufacturers.invalid/sunfield-value-mechanics",
                        "Value-focused equipment and tools for early professional shops."
                ),
                manufacturer(
                        "commonwealth_scale_company",
                        "Commonwealth Scale Company",
                        1937,
                        BuiltInRegionCatalog.PRAIRIE_COMMONWEALTH,
                        "Commonwealth Center",
                        EnumSet.of(ManufacturerCategory.SCALES),
                        ManufacturerTier.NATIONAL,
                        EngineeringPhilosophy.PRECISION_ENGINEERING,
                        "Commonwealth Scale Company started by building certified livestock market scales before expanding into retail and bench weighing. Its engineers prize repeatable readings, conservative tolerances, and clear service records over decorative features.",
                        "Measure once, trust always.",
                        branding("#1F3D5A", "#E9E3D0", "#C89B3C", "Blue housings, cream dials, and small brass calibration seals"),
                        "bench scales",
                        "retail weigh stations",
                        "calibration fixtures",
                        "Trusted by shops that treat weighing accuracy as part of their reputation.",
                        "https://manufacturers.invalid/commonwealth-scale-company",
                        "Precision weighing equipment with conservative service documentation."
                ),
                manufacturer(
                        "railfield_conveyor_and_cart",
                        "Railfield Conveyor And Cart",
                        1954,
                        BuiltInRegionCatalog.PRAIRIE_COMMONWEALTH,
                        "Railfield",
                        EnumSet.of(ManufacturerCategory.MATERIAL_HANDLING),
                        ManufacturerTier.NATIONAL,
                        EngineeringPhilosophy.HIGH_THROUGHPUT,
                        "Railfield Conveyor And Cart was founded near a freight depot where processors needed carts that could survive ramps, washdowns, and long shifts. The company later specialized in modular conveyors that keep product moving without requiring a huge maintenance crew.",
                        "Keep the line moving.",
                        branding("#38434F", "#D84A2B", "#F0E7D8", "Charcoal frames, red drive covers, and freight-stencil labels"),
                        "washdown carts",
                        "modular conveyors",
                        "line transfer tables",
                        "Known for practical throughput improvements in busy regional plants.",
                        "https://manufacturers.invalid/railfield-conveyor-and-cart",
                        "Material-handling systems for shops that need orderly movement and quick cleanup."
                ),
                manufacturer(
                        "meadowpack_supply",
                        "Meadowpack Supply",
                        1981,
                        BuiltInRegionCatalog.PRAIRIE_COMMONWEALTH,
                        "Meadow Crossing",
                        EnumSet.of(ManufacturerCategory.PACKAGING),
                        ManufacturerTier.LOCAL,
                        EngineeringPhilosophy.SERVICEABILITY,
                        "Meadowpack Supply began as a local wrapper-roll distributor that repaired labelers from the back of the delivery truck. It keeps close customer notes and builds packaging tools around fast blade changes, obvious wear parts, and cheerful service calls.",
                        "Wrapped right by people nearby.",
                        branding("#79A35A", "#FFFFFF", "#C9452E", "Fresh green labels, white roll guards, and red service tags"),
                        "counter wrapping tools",
                        "label roll dispensers",
                        "tray sealing accessories",
                        "Respected for unusually responsive service in small towns and farm markets.",
                        "https://manufacturers.invalid/meadowpack-supply",
                        "Regional packaging support with an emphasis on serviceable daily-use tools."
                ),
                manufacturer(
                        "granary_guard_safety",
                        "Granary Guard Safety",
                        2002,
                        BuiltInRegionCatalog.PRAIRIE_COMMONWEALTH,
                        "Granary County",
                        EnumSet.of(ManufacturerCategory.SAFETY_EQUIPMENT),
                        ManufacturerTier.LOCAL,
                        EngineeringPhilosophy.INDUSTRIAL_SIMPLICITY,
                        "Granary Guard Safety was formed by former plant supervisors who wanted safety gear that crews would actually wear. The company focuses on straightforward guards, aprons, gloves, and signage that work in small facilities without complicated programs.",
                        "Simple gear, safer shifts.",
                        branding("#C74C24", "#1F252A", "#F3D37A", "Safety-orange panels, black straps, and harvest-gold warning icons"),
                        "cut-resistant gloves",
                        "washdown aprons",
                        "floor safety markers",
                        "Appreciated for practical safety supplies that do not feel over-engineered.",
                        "https://manufacturers.invalid/granary-guard-safety",
                        "Plainspoken safety equipment for everyday processing work."
                ),
                manufacturer(
                        "iron_valley_precision_machinery",
                        "Iron Valley Precision Machinery",
                        1898,
                        BuiltInRegionCatalog.IRON_VALLEY,
                        "Foundry City",
                        EnumSet.of(ManufacturerCategory.PROCESSING_EQUIPMENT, ManufacturerCategory.SPECIALTY_EQUIPMENT),
                        ManufacturerTier.INDUSTRY_LEADER,
                        EngineeringPhilosophy.PRECISION_ENGINEERING,
                        "Iron Valley Precision Machinery descends from a tool-and-die shop that served rail yards and food plants through three industrial eras. Its modern machines are expensive, quiet, and meticulously aligned because the company believes precision should reduce waste before anyone notices it.",
                        "Exact work, less waste.",
                        branding("#20242B", "#B9B7AD", "#8B1E2D", "Dark enamel panels, satin-steel trim, and narrow crimson alignment marks"),
                        "precision grinders",
                        "fabrication saws",
                        "servo-indexed processing fixtures",
                        "Considered a premium benchmark for processors that can justify careful engineering.",
                        "https://manufacturers.invalid/iron-valley-precision-machinery",
                        "Premium processing and specialty equipment with exacting mechanical tolerances."
                ),
                manufacturer(
                        "millstone_benchworks",
                        "Millstone Benchworks",
                        1926,
                        BuiltInRegionCatalog.IRON_VALLEY,
                        "Millstone",
                        EnumSet.of(ManufacturerCategory.SMALLWARES, ManufacturerCategory.SPECIALTY_EQUIPMENT),
                        ManufacturerTier.REGIONAL,
                        EngineeringPhilosophy.FAMILY_CRAFTSMANSHIP,
                        "Millstone Benchworks began with two brothers building butcher blocks from salvaged maple and quarry-town hardware. The company still treats benches, stands, and fixtures like long-lived shop furniture rather than disposable accessories.",
                        "Work rests on good wood and better joinery.",
                        branding("#7B4B2A", "#E2C99D", "#2E3138", "Warm wood tones, black corner brackets, and maker-stamped edges"),
                        "work benches",
                        "fixture stands",
                        "small shop tables",
                        "Known for handsome fixtures that feel handmade without being fragile.",
                        "https://manufacturers.invalid/millstone-benchworks",
                        "Shop fixtures and smallwares built with careful joinery and industrial hardware."
                ),
                manufacturer(
                        "forgebright_cutlery",
                        "Forgebright Cutlery",
                        1907,
                        BuiltInRegionCatalog.IRON_VALLEY,
                        "Forge Hollow",
                        EnumSet.of(ManufacturerCategory.KNIVES_AND_CUTLERY),
                        ManufacturerTier.NATIONAL,
                        EngineeringPhilosophy.FAMILY_CRAFTSMANSHIP,
                        "Forgebright Cutlery traces its reputation to valley blade smiths who supplied rail dining rooms and market butchers. Its knives are still ground in small batches, marked by hand, and sold with a strong preference for balance over ornament.",
                        "A true edge earns its keep.",
                        branding("#D9D3C7", "#4D4A45", "#B34A2E", "Cream blade wraps, charcoal handles, and small ember-red forge marks"),
                        "breaking knives",
                        "boning knives",
                        "sharpening steels",
                        "Renowned for knives that professionals remember by feel more than by label.",
                        "https://manufacturers.invalid/forgebright-cutlery",
                        "Hand-finished professional cutlery for shops that value balance and edge life."
                ),
                manufacturer(
                        "bridgeworks_sanitation",
                        "Bridgeworks Sanitation",
                        1944,
                        BuiltInRegionCatalog.IRON_VALLEY,
                        "Bridgeworks",
                        EnumSet.of(ManufacturerCategory.SANITATION, ManufacturerCategory.UTILITIES),
                        ManufacturerTier.NATIONAL,
                        EngineeringPhilosophy.SERVICEABILITY,
                        "Bridgeworks Sanitation was created when valley processors needed wash systems that could be repaired between shifts rather than replaced after each upgrade. It designs pumps, foaming stations, and hose reels with labeled access panels and parts common across product lines.",
                        "Clean systems, open panels.",
                        branding("#1D5E6B", "#E8F1F2", "#F18F01", "Teal equipment bodies, white hose guides, and amber maintenance labels"),
                        "foam stations",
                        "washdown pumps",
                        "sanitation utility reels",
                        "Trusted by maintenance crews for layouts that make cleaning equipment easy to keep alive.",
                        "https://manufacturers.invalid/bridgeworks-sanitation",
                        "Sanitation and washdown utility equipment designed around service access."
                ),
                manufacturer(
                        "quarryline_liftworks",
                        "Quarryline Liftworks",
                        1973,
                        BuiltInRegionCatalog.IRON_VALLEY,
                        "Quarry Exchange",
                        EnumSet.of(ManufacturerCategory.MATERIAL_HANDLING, ManufacturerCategory.SAFETY_EQUIPMENT),
                        ManufacturerTier.REGIONAL,
                        EngineeringPhilosophy.BUILT_TO_LAST,
                        "Quarryline Liftworks adapted stone-yard lift tables and pallet equipment for food processors that needed safer handling in cramped rooms. Its products are overbuilt, slow to change, and valued anywhere floor abuse is a normal part of work.",
                        "Lift steady, stand clear.",
                        branding("#59636E", "#D7D0C4", "#E0A72E", "Slate-gray lift arms, cream guards, and yellow caution striping"),
                        "lift tables",
                        "tub tilters",
                        "guarded material lifts",
                        "Known for rugged lift equipment that survives hard floors and impatient crews.",
                        "https://manufacturers.invalid/quarryline-liftworks",
                        "Material lifts and handling safety gear for demanding shop floors."
                ),
                manufacturer(
                        "cinderlane_controls",
                        "Cinderlane Controls",
                        1989,
                        BuiltInRegionCatalog.IRON_VALLEY,
                        "Cinder Hollow",
                        EnumSet.of(ManufacturerCategory.UTILITIES, ManufacturerCategory.SPECIALTY_EQUIPMENT),
                        ManufacturerTier.REGIONAL,
                        EngineeringPhilosophy.INNOVATION_FIRST,
                        "Cinderlane Controls grew from an electrical panel shop that served old valley factories during modernization projects. It specializes in compact utility controls that add monitoring and shutoff features without demanding a full plant redesign.",
                        "Smarter panels for older rooms.",
                        branding("#252A34", "#56A3A6", "#F2E9DC", "Dark control boxes, aqua indicator lights, and cream terminal maps"),
                        "utility panels",
                        "monitoring controls",
                        "retrofit shutoff systems",
                        "Regarded as a clever modernization partner for older facilities with limited space.",
                        "https://manufacturers.invalid/cinderlane-controls",
                        "Utility and specialty control systems for careful retrofit projects."
                ),
                manufacturer(
                        "rivergate_cold_chain",
                        "Rivergate Cold Chain",
                        1931,
                        BuiltInRegionCatalog.GREAT_RIVER_BASIN,
                        "Rivergate City",
                        EnumSet.of(ManufacturerCategory.REFRIGERATION),
                        ManufacturerTier.INDUSTRY_LEADER,
                        EngineeringPhilosophy.ENERGY_EFFICIENCY,
                        "Rivergate Cold Chain began by maintaining ice warehouses along the basin before becoming an early mechanical refrigeration specialist. Its identity is built around stable temperatures, low operating cost, and cold rooms that do not waste power fighting themselves.",
                        "Hold the cold, spare the meter.",
                        branding("#0E5A7A", "#DDEEF4", "#6CC4A1", "Deep blue compressor badges, pale insulated panels, and mint service icons"),
                        "walk-in refrigeration",
                        "cold-room controls",
                        "efficient compressor racks",
                        "Recognized as a high-trust refrigeration specialist with a long cold-chain memory.",
                        "https://manufacturers.invalid/rivergate-cold-chain",
                        "Refrigeration systems focused on temperature stability and energy performance."
                ),
                manufacturer(
                        "willowbend_wrapping_company",
                        "Willowbend Wrapping Company",
                        1958,
                        BuiltInRegionCatalog.GREAT_RIVER_BASIN,
                        "Willow Bend",
                        EnumSet.of(ManufacturerCategory.PACKAGING),
                        ManufacturerTier.REGIONAL,
                        EngineeringPhilosophy.INDUSTRIAL_SIMPLICITY,
                        "Willowbend Wrapping Company started in a river-market warehouse making paper cutters and roll holders for family stores. It remains devoted to simple packaging fixtures that can be cleaned quickly, mounted anywhere, and explained in one minute.",
                        "Wrap clean, move on.",
                        branding("#8CA65D", "#F7F2E7", "#3F5F72", "Willow-green trim, cream roll shields, and river-blue instruction plates"),
                        "paper cutters",
                        "wrap dispensers",
                        "counter packaging fixtures",
                        "Favored by shops that want packaging tools to be obvious, sturdy, and low drama.",
                        "https://manufacturers.invalid/willowbend-wrapping-company",
                        "Simple packaging fixtures for retail counters and prep rooms."
                ),
                manufacturer(
                        "ferry_marker_scales",
                        "Ferry Marker Scales",
                        1886,
                        BuiltInRegionCatalog.GREAT_RIVER_BASIN,
                        "Old Ferry",
                        EnumSet.of(ManufacturerCategory.SCALES),
                        ManufacturerTier.LOCAL,
                        EngineeringPhilosophy.BUILT_TO_LAST,
                        "Ferry Marker Scales was founded to weigh river freight before its platform scales found a second life in market houses. The company is small, stubborn, and proud of instruments that can be recalibrated long after newer models are forgotten.",
                        "Weight with a memory.",
                        branding("#3D405B", "#F2CC8F", "#81B29A", "Blue-gray castings, brass tick marks, and green inspection stamps"),
                        "platform scales",
                        "counter scales",
                        "manual calibration kits",
                        "Known locally for durable scales with old-fashioned service ledgers.",
                        "https://manufacturers.invalid/ferry-marker-scales",
                        "Long-lived weighing tools with a strong repair tradition."
                ),
                manufacturer(
                        "basin_bright_hygiene",
                        "Basin Bright Hygiene",
                        1979,
                        BuiltInRegionCatalog.GREAT_RIVER_BASIN,
                        "Basin Market",
                        EnumSet.of(ManufacturerCategory.SANITATION),
                        ManufacturerTier.REGIONAL,
                        EngineeringPhilosophy.BUDGET_VALUE,
                        "Basin Bright Hygiene emerged from janitorial supply routes that served small grocers, lockers, and fish markets around the river basin. It keeps costs practical while giving operators clear procedures, reliable dispensers, and supplies that arrive when promised.",
                        "Clean enough to count on.",
                        branding("#3A86FF", "#F8F9FA", "#43AA8B", "Bright blue labels, white containers, and green procedure cards"),
                        "sanitation dispensers",
                        "cleaning supply stations",
                        "procedure kits",
                        "Respected for affordable hygiene systems that make compliance less intimidating.",
                        "https://manufacturers.invalid/basin-bright-hygiene",
                        "Practical sanitation supplies for shops that need clarity and value."
                ),
                manufacturer(
                        "orchard_steel_smallwares",
                        "Orchard Steel Smallwares",
                        1949,
                        BuiltInRegionCatalog.GREAT_RIVER_BASIN,
                        "Orchard Ford",
                        EnumSet.of(ManufacturerCategory.SMALLWARES, ManufacturerCategory.KNIVES_AND_CUTLERY),
                        ManufacturerTier.NATIONAL,
                        EngineeringPhilosophy.INDUSTRIAL_SIMPLICITY,
                        "Orchard Steel Smallwares began stamping trays, hooks, scoops, and bench tools for produce markets that also ran meat counters. Its catalog is broad, plain, and beloved by managers who prefer every tool to stack, hang, or wash without fuss.",
                        "Plain tools, busy counters.",
                        branding("#5A6F3B", "#C8D5B9", "#8D5A32", "Olive handles, pale green cartons, and orchard-brown stamped marks"),
                        "hooks and scoops",
                        "bench trays",
                        "utility knives",
                        "Known for everyday tools that disappear into the rhythm of the shop.",
                        "https://manufacturers.invalid/orchard-steel-smallwares",
                        "Durable smallwares and simple cutlery for high-use retail counters."
                ),
                manufacturer(
                        "landing_lane_labels",
                        "Landing Lane Labels",
                        1996,
                        BuiltInRegionCatalog.GREAT_RIVER_BASIN,
                        "Bridge Landing",
                        EnumSet.of(ManufacturerCategory.PACKAGING, ManufacturerCategory.SCALES),
                        ManufacturerTier.LOCAL,
                        EngineeringPhilosophy.SERVICEABILITY,
                        "Landing Lane Labels was founded by scale technicians who realized label problems caused as much daily frustration as mechanical failures. The company builds compact labelers and printer-scale accessories with quick access doors and generous troubleshooting diagrams.",
                        "Labels should never hold the line.",
                        branding("#6A4C93", "#F6E7CB", "#1982C4", "Purple covers, cream media guides, and blue status arrows"),
                        "label printers",
                        "scale label adapters",
                        "retail roll handling",
                        "Appreciated by counter crews for label equipment that can be fixed during a rush.",
                        "https://manufacturers.invalid/landing-lane-labels",
                        "Retail label and scale accessories designed for fast service recovery."
                ),
                manufacturer(
                        "mesa_thermal_systems",
                        "Mesa Thermal Systems",
                        1961,
                        BuiltInRegionCatalog.HIGH_PLAINS_TERRITORY,
                        "Mesa City",
                        EnumSet.of(ManufacturerCategory.REFRIGERATION, ManufacturerCategory.UTILITIES),
                        ManufacturerTier.NATIONAL,
                        EngineeringPhilosophy.ENERGY_EFFICIENCY,
                        "Mesa Thermal Systems was created to keep remote high-plains facilities cold through heat, dust, and limited service access. Its engineers favor efficient thermal loops, clear alarms, and cabinets that tolerate harsh utility rooms.",
                        "Cold control for hard country.",
                        branding("#A44A3F", "#F2E2C4", "#247BA0", "Red mesa cabinets, sand-colored panels, and blue temperature icons"),
                        "remote refrigeration",
                        "utility cooling loops",
                        "temperature alarm panels",
                        "Known for efficient cold systems that perform well far from major service hubs.",
                        "https://manufacturers.invalid/mesa-thermal-systems",
                        "Refrigeration and utility cooling systems for demanding climates."
                ),
                manufacturer(
                        "rangegate_processing_systems",
                        "Rangegate Processing Systems",
                        1984,
                        BuiltInRegionCatalog.HIGH_PLAINS_TERRITORY,
                        "Rangegate",
                        EnumSet.of(ManufacturerCategory.PROCESSING_EQUIPMENT, ManufacturerCategory.MATERIAL_HANDLING),
                        ManufacturerTier.INDUSTRY_LEADER,
                        EngineeringPhilosophy.HIGH_THROUGHPUT,
                        "Rangegate Processing Systems formed when high-volume ranch processors wanted integrated cutting, moving, and staging equipment from one accountable builder. The company is known for throughput studies, tough conveyors, and processing lines that feel planned rather than assembled piece by piece.",
                        "Plan the line, win the day.",
                        branding("#2B2D42", "#EF8354", "#BFC0C0", "Dark frames, orange motion guards, and brushed metal route plaques"),
                        "integrated processing lines",
                        "fabrication conveyors",
                        "high-capacity staging systems",
                        "Respected as a serious industrial partner for processors with expansion plans.",
                        "https://manufacturers.invalid/rangegate-processing-systems",
                        "High-throughput processing and handling systems for large operations."
                ),
                manufacturer(
                        "sagebrush_knife_and_tool",
                        "Sagebrush Knife And Tool",
                        1971,
                        BuiltInRegionCatalog.HIGH_PLAINS_TERRITORY,
                        "Sage Junction",
                        EnumSet.of(ManufacturerCategory.KNIVES_AND_CUTLERY, ManufacturerCategory.SMALLWARES),
                        ManufacturerTier.LOCAL,
                        EngineeringPhilosophy.SERVICEABILITY,
                        "Sagebrush Knife And Tool began sharpening knives from a truck that followed auction and processing schedules across the plains. Its tools are designed around easy maintenance, replaceable handles, and steel that field sharpeners understand.",
                        "A sharp tool should be easy to keep.",
                        branding("#6B705C", "#FFE8D6", "#CB997E", "Sage handles, light leather wraps, and coppery service stamps"),
                        "serviceable knives",
                        "field sharpening kits",
                        "replacement handles",
                        "Loved by crews who would rather maintain tools than replace them.",
                        "https://manufacturers.invalid/sagebrush-knife-and-tool",
                        "Serviceable knives and tool kits rooted in mobile sharpening culture."
                ),
                manufacturer(
                        "stockyard_packaging_works",
                        "Stockyard Packaging Works",
                        1991,
                        BuiltInRegionCatalog.HIGH_PLAINS_TERRITORY,
                        "Stockyard Crossing",
                        EnumSet.of(ManufacturerCategory.PACKAGING, ManufacturerCategory.SAFETY_EQUIPMENT),
                        ManufacturerTier.LOCAL,
                        EngineeringPhilosophy.BUDGET_VALUE,
                        "Stockyard Packaging Works began by supplying rugged bags, trays, and counter supplies to auction-town processors with inconsistent order volumes. It builds practical packaging gear and safety accessories for facilities that need durability before refinement.",
                        "Tough packs, fair prices.",
                        branding("#8D5524", "#E6CCB2", "#C1121F", "Brown cartons, tan guards, and red lot-number badges"),
                        "bulk packaging supplies",
                        "rugged tray handling",
                        "basic counter safety accessories",
                        "Known for affordable packaging support that tolerates rough handling.",
                        "https://manufacturers.invalid/stockyard-packaging-works",
                        "Durable packaging supplies and practical accessories for volume swings."
                ),
                manufacturer(
                        "drawline_utility_fabricators",
                        "Drawline Utility Fabricators",
                        1952,
                        BuiltInRegionCatalog.HIGH_PLAINS_TERRITORY,
                        "Draw Station",
                        EnumSet.of(ManufacturerCategory.UTILITIES, ManufacturerCategory.SANITATION),
                        ManufacturerTier.REGIONAL,
                        EngineeringPhilosophy.INDUSTRIAL_SIMPLICITY,
                        "Drawline Utility Fabricators learned to build water, drain, and hose systems for processors where repairs had to happen with common parts. The company avoids delicate assemblies and favors visible plumbing, bolt-on guards, and labeled flow paths.",
                        "If it flows, make it obvious.",
                        branding("#355070", "#E56B6F", "#EAAC8B", "Blue pipe maps, coral valve tags, and peach warning bands"),
                        "washdown plumbing",
                        "drain utility frames",
                        "hose routing systems",
                        "Valued by practical operators who want utilities that can be understood at a glance.",
                        "https://manufacturers.invalid/drawline-utility-fabricators",
                        "Utility and sanitation fabrication for straightforward maintenance."
                ),
                manufacturer(
                        "territory_shield_equipment",
                        "Territory Shield Equipment",
                        2008,
                        BuiltInRegionCatalog.HIGH_PLAINS_TERRITORY,
                        "Territory Center",
                        EnumSet.of(ManufacturerCategory.SAFETY_EQUIPMENT, ManufacturerCategory.MATERIAL_HANDLING),
                        ManufacturerTier.LOCAL,
                        EngineeringPhilosophy.INNOVATION_FIRST,
                        "Territory Shield Equipment was founded by younger fabricators who saw small plants improvising guards and cart brakes that should have been standard. It brings modern safety ideas into simple bolt-on products for older rooms and fast-growing shops.",
                        "Guard the work before it bites.",
                        branding("#111827", "#F9C74F", "#4D96FF", "Black guard plates, yellow hazard geometry, and blue adjustment knobs"),
                        "machine guards",
                        "cart brake kits",
                        "retrofit safety rails",
                        "Seen as nimble and inventive, especially by shops modernizing older equipment.",
                        "https://manufacturers.invalid/territory-shield-equipment",
                        "Safety retrofits and handling accessories for changing shop floors."
                ),
                manufacturer(
                        "timber_ridge_refrigeration",
                        "Timber Ridge Refrigeration",
                        1920,
                        BuiltInRegionCatalog.TIMBER_RIDGE,
                        "Timber Ridge",
                        EnumSet.of(ManufacturerCategory.REFRIGERATION),
                        ManufacturerTier.REGIONAL,
                        EngineeringPhilosophy.BUILT_TO_LAST,
                        "Timber Ridge Refrigeration began installing cold rooms for lake-country dairies and rural lockers that could not afford repeat failures. Its equipment is conservative, sturdy, and known for compressors that sound the same after years of steady work.",
                        "Cold rooms that grow old gracefully.",
                        branding("#264653", "#E9C46A", "#2A9D8F", "Deep green-blue panels, gold badges, and teal temperature marks"),
                        "walk-in boxes",
                        "rural locker refrigeration",
                        "service-friendly condensers",
                        "Known for long-lived cold rooms in smaller facilities and lake-country shops.",
                        "https://manufacturers.invalid/timber-ridge-refrigeration",
                        "Conservative refrigeration equipment for rural lockers and family shops."
                ),
                manufacturer(
                        "cedar_harbor_paperworks",
                        "Cedar Harbor Paperworks",
                        1939,
                        BuiltInRegionCatalog.TIMBER_RIDGE,
                        "Cedar Harbor",
                        EnumSet.of(ManufacturerCategory.PACKAGING, ManufacturerCategory.SMALLWARES),
                        ManufacturerTier.LOCAL,
                        EngineeringPhilosophy.FAMILY_CRAFTSMANSHIP,
                        "Cedar Harbor Paperworks grew from a family print shop that made butcher paper, counter cards, and wrapped-goods supplies for lake towns. Its catalog has a careful, tactile personality built around good paper, tidy rolls, and packaging that feels local.",
                        "Wrap with a shopkeeper's hand.",
                        branding("#356859", "#FFF3B0", "#B56576", "Cedar-green wrappers, warm paper labels, and rose-red roll ends"),
                        "butcher paper rolls",
                        "counter cards",
                        "paper wrapping accessories",
                        "Appreciated for packaging supplies that bring warmth to small retail counters.",
                        "https://manufacturers.invalid/cedar-harbor-paperworks",
                        "Paper packaging and smallwares with a family-shop presentation style."
                ),
                manufacturer(
                        "pinegate_equipment_company",
                        "Pinegate Equipment Company",
                        1964,
                        BuiltInRegionCatalog.TIMBER_RIDGE,
                        "Pinegate",
                        EnumSet.of(ManufacturerCategory.PROCESSING_EQUIPMENT),
                        ManufacturerTier.NATIONAL,
                        EngineeringPhilosophy.SERVICEABILITY,
                        "Pinegate Equipment Company earned a following by designing midrange processing machines that could be opened, cleaned, and repaired without a specialized crew. Its service manuals are famous for clear diagrams and calm language.",
                        "Open it, clean it, fix it.",
                        branding("#1B4332", "#D8F3DC", "#F77F00", "Forest-green housings, pale manual covers, and orange service latches"),
                        "midrange grinders",
                        "serviceable mixers",
                        "clear-maintenance processing machines",
                        "Trusted by independent shops that want professional equipment without helpless service dependence.",
                        "https://manufacturers.invalid/pinegate-equipment-company",
                        "Serviceable processing equipment with unusually clear maintenance documentation."
                ),
                manufacturer(
                        "maplewood_cutlery_house",
                        "Maplewood Cutlery House",
                        1881,
                        BuiltInRegionCatalog.TIMBER_RIDGE,
                        "Maple Center",
                        EnumSet.of(ManufacturerCategory.KNIVES_AND_CUTLERY),
                        ManufacturerTier.INDUSTRY_LEADER,
                        EngineeringPhilosophy.FAMILY_CRAFTSMANSHIP,
                        "Maplewood Cutlery House is the oldest active manufacturer in the catalog and began with hand-forged shop knives sold through timber-town hardware stores. It remains a premium cutlery house where handles, balance, and finishing receive as much attention as steel.",
                        "Made by hand, remembered by hand.",
                        branding("#5C4033", "#F5E6CC", "#9C6644", "Maple-brown handles, parchment sheaths, and bronze maker marks"),
                        "premium cutlery",
                        "hand-finished knives",
                        "legacy sharpening steels",
                        "Revered for handcrafted knives that become heirloom tools in professional shops.",
                        "https://manufacturers.invalid/maplewood-cutlery-house",
                        "Premium handcrafted cutlery with deep regional history."
                ),
                manufacturer(
                        "clearwater_compliance_systems",
                        "Clearwater Compliance Systems",
                        1987,
                        BuiltInRegionCatalog.TIMBER_RIDGE,
                        "Clearwater",
                        EnumSet.of(ManufacturerCategory.SANITATION, ManufacturerCategory.SAFETY_EQUIPMENT),
                        ManufacturerTier.NATIONAL,
                        EngineeringPhilosophy.PRECISION_ENGINEERING,
                        "Clearwater Compliance Systems was founded by sanitation engineers who believed clean facilities needed repeatable systems rather than anxious guesswork. Its products pair precise dispensing, clear station layouts, and documentation that future inspectors can understand.",
                        "Clean records, cleaner rooms.",
                        branding("#006D77", "#EDF6F9", "#FFDDD2", "Blue-green station panels, pale documentation sleeves, and salmon checklist tabs"),
                        "chemical dispensing",
                        "sanitation stations",
                        "compliance documentation fixtures",
                        "Respected for reliability and a calm, professional approach to sanitation rules.",
                        "https://manufacturers.invalid/clearwater-compliance-systems",
                        "Sanitation and safety systems with strong procedural documentation."
                ),
                manufacturer(
                        "northwood_specialty_works",
                        "Northwood Specialty Works",
                        1976,
                        BuiltInRegionCatalog.TIMBER_RIDGE,
                        "Northwood",
                        EnumSet.of(ManufacturerCategory.SPECIALTY_EQUIPMENT, ManufacturerCategory.MATERIAL_HANDLING),
                        ManufacturerTier.REGIONAL,
                        EngineeringPhilosophy.INNOVATION_FIRST,
                        "Northwood Specialty Works grew from a custom fabrication shop that solved odd problems for remote lockers and seasonal processors. It builds unusual fixtures, compact handling equipment, and one-off specialty machines with a reputation for clever solutions that still feel sturdy.",
                        "Odd jobs deserve proper machines.",
                        branding("#2D6A4F", "#B7E4C7", "#6930C3", "Deep green frames, pale green guards, and violet prototype tags"),
                        "custom fixtures",
                        "compact handling aids",
                        "specialty processing adapters",
                        "Known as the inventive shop to call when ordinary equipment does not fit.",
                        "https://manufacturers.invalid/northwood-specialty-works",
                        "Specialty equipment and compact handling systems for unusual shop constraints."
                )
        );
    }

    private static Manufacturer manufacturer(
            String id,
            String displayName,
            int foundingYear,
            String regionId,
            String localityName,
            Set<ManufacturerCategory> categories,
            ManufacturerTier marketTier,
            EngineeringPhilosophy engineeringPhilosophy,
            String companyHistory,
            String slogan,
            ManufacturerBranding branding,
            String specialtyOne,
            String specialtyTwo,
            String specialtyThree,
            String reputation,
            String websitePlaceholder,
            String catalogDescriptionPlaceholder
    ) {
        return new Manufacturer(
                id,
                displayName,
                foundingYear,
                new Headquarters(regionId, localityName),
                categories,
                marketTier,
                engineeringPhilosophy,
                companyHistory,
                slogan,
                branding,
                List.of(specialtyOne, specialtyTwo, specialtyThree),
                reputation,
                websitePlaceholder,
                catalogDescriptionPlaceholder
        );
    }

    private static ManufacturerBranding branding(
            String primaryColor,
            String secondaryColor,
            String accentColor,
            String visualIdentity
    ) {
        return new ManufacturerBranding(primaryColor, secondaryColor, accentColor, visualIdentity);
    }
}
