package com.butchercraft.world.simulation.scheduler;

import java.util.Arrays;
import java.util.Locale;

public enum WorkFailureCode {
    UNKNOWN_WORK, UNKNOWN_WORK_TYPE, UNKNOWN_STAGE, HANDLER_NOT_REGISTERED, INVALID_PAYLOAD,
    INVALID_STATUS, INVALID_STATUS_TRANSITION, INVALID_TICK, BACKWARD_TICK, DUPLICATE_WORK_ID,
    DUPLICATE_SUBMISSION_SEQUENCE, BUDGET_EXHAUSTED, RETRY_LIMIT_REACHED, WORK_EXPIRED,
    HANDLER_REJECTED, HANDLER_EXCEPTION, PERSISTENCE_FAILURE, UNSUPPORTED_SCHEMA,
    VALIDATION_FAILED, INTERNAL_INVARIANT_VIOLATION, INVALID_EFFECT_DECLARATION,
    MISSING_INVOCATION_IDENTITY, MISSING_REQUIRED_EFFECT_IDENTITY, HANDLER_EFFECT_IDENTITY_CONFLICT,
    HANDLER_RETRY_NOT_PERMITTED, HANDLER_DEFERRAL_NOT_PERMITTED, HANDLER_GENERATED_WORK_NOT_PERMITTED,
    HANDLER_TRANSACTION_EVIDENCE_MISSING, HANDLER_IDEMPOTENCY_EVIDENCE_MISSING,
    HANDLER_EFFECT_OUTCOME_UNKNOWN, NON_REPEATABLE_OUTCOME_UNKNOWN,
    SCHEDULER_AUTHORITY_ALREADY_EXECUTING, SCHEDULER_AUTHORITY_MISMATCH, DUPLICATE_ACTIVE_INVOCATION,
    ILLEGAL_GENERATED_WORK, ACTIVE_CANCELLATION_UNSUPPORTED, PERSISTED_INVALID_RUNTIME_STATE,
    UNSUPPORTED_EFFECT_POLICY_SCHEMA, TRANSACTION_RESULT_EVIDENCE_MISMATCH,
    PRODUCTION_COMPLETION_WITHOUT_AUTHORITATIVE_RESULT, SCHEDULER_OBSERVATION_INFERENCE_ATTEMPTED,
    AUTOMATIC_RETRY_BLOCKED_BY_UNKNOWN_OUTCOME, MISSING_AUTHORITATIVE_RESULT, UNKNOWN;

    public String serializedName() {
        return name().toLowerCase(Locale.ROOT);
    }

    public static WorkFailureCode fromSerializedName(String value) {
        return Arrays.stream(values()).filter(code -> code.serializedName().equals(value)).findFirst()
                .orElseThrow(() -> new IllegalArgumentException("Unknown work failure code: " + value));
    }
}
