package com.butchercraft.world.transaction.binding;

public enum TransactionBindingFailureCode {
    UNSUPPORTED_SCHEMA,
    INVALID_BINDING,
    MISSING_BINDING_COMPONENT,
    MISSING_VALIDATION_INPUT,
    HIDDEN_VALIDATION_INPUT,
    PROPOSAL_IDENTITY_MISMATCH,
    INVENTORY_FRESHNESS_IDENTITY_MISMATCH,
    VALIDATION_PLAN_IDENTITY_MISMATCH,
    VALIDATION_CONSUMPTION_AUTHORITY_INVALID,
    VALIDATION_CONSUMPTION_AUTHORITY_CONSUMED,
    RESULT_EVIDENCE_MISMATCH,
    RESULT_EVIDENCE_DIGEST_MISMATCH,
    TRANSACTION_IDENTITY_CONFLICT,
    CONTENT_IDENTITY_CONFLICT
}
