package com.butchercraft.world.execution;

public enum ExecutionRegistryCompatibilityFailureCode {
    UNSUPPORTED_EXECUTION_SCHEMA,
    RUNTIME_CONFIGURATION_MISMATCH,
    UNKNOWN_REGISTRY_OBSERVATION,
    LEGACY_PROFILE_DIGEST_MISMATCH,
    REFERENCED_HANDLER_MISSING,
    HANDLER_OPERATION_TYPE_MISMATCH,
    HANDLER_CONTRACT_MISMATCH,
    OPERATION_CONTRACT_BINDING_INVALID,
    REGISTRY_METADATA_CORRUPT
}
