package com.butchercraft.world.planning;

final class PlanningEnums {
    private PlanningEnums() {
    }
}

enum NeedType { OUTSTANDING_ORDER_LINE, PRODUCTION_OUTPUT_REQUIREMENT, INVENTORY_SHORTAGE,
    CONTRACT_OBLIGATION, SHIPMENT_REQUIREMENT, PURCHASE_REQUIREMENT, MAINTENANCE_REQUIREMENT,
    UTILITY_REQUIREMENT, INSPECTION_REQUIREMENT }
enum ConstraintType { UNKNOWN_REFERENCE, UNSUPPORTED_NEED_TYPE, UNSUPPORTED_PLAN_CATEGORY,
    NO_COMPATIBLE_PROCESS, ACTOR_CAPABILITY_MISSING, BUSINESS_NOT_OPERATIONAL, BUSINESS_CLOSED,
    BUSINESS_IN_MAINTENANCE, NO_ACTIVE_SHIFT, WORKFORCE_INSUFFICIENT, INPUT_INVENTORY_UNAVAILABLE,
    INSUFFICIENT_INPUT, OUTPUT_INVENTORY_UNAVAILABLE, DESTINATION_CAPACITY_INSUFFICIENT,
    PROCESS_BATCH_INCOMPATIBLE, PLAN_ALREADY_EXISTS, REQUIRED_BY_TICK_UNACHIEVABLE,
    SCHEDULER_CAPACITY_UNAVAILABLE, SUBMISSION_ADAPTER_UNAVAILABLE, CYCLE_BUDGET_EXHAUSTED,
    RECURSION_DEPTH_EXHAUSTED, INVALID_QUANTITY, UNIT_MISMATCH, EXPIRED_NEED, POLICY_REJECTED }
enum OpportunityType { PRODUCTION }
enum PlanCategory { PRODUCTION, SHIPMENT, PURCHASE, MAINTENANCE, UTILITY, INSPECTION }
enum ConstraintScope { NEED, OPPORTUNITY, CANDIDATE, SUBMISSION, CYCLE }
enum CandidateFeasibility { UNEVALUATED, VALID, BLOCKED, INVALID, UNSUPPORTED }
enum ApprovalDisposition { EXECUTABLE, ADVISORY }
enum NeedResolutionStatus { UNRESOLVED, PARTIALLY_RESOLVED, FULLY_RESOLVED, BLOCKED, INVALID, EXPIRED, FAILED }
enum PlanningSubmissionStatus { PENDING, SUBMITTING, SUBMITTED, REJECTED, DEFERRED, FAILED, CANCELLED;
    boolean terminal() { return this == SUBMITTED || this == REJECTED || this == FAILED || this == CANCELLED; } }
enum PlanningCycleStatus { CREATED, OBSERVING, DETECTING_NEEDS, DETECTING_CONSTRAINTS,
    DISCOVERING_OPPORTUNITIES, GENERATING_CANDIDATES, EVALUATING, RANKING, SELECTING, SUBMITTING,
    COMPLETED, COMPLETED_WITH_REMAINDER, FAILED;
    boolean terminal() { return this == COMPLETED || this == COMPLETED_WITH_REMAINDER || this == FAILED; } }
enum PlanningFailureCode { DUPLICATE_CYCLE_ID, DUPLICATE_ARTIFACT_ID, UNKNOWN_POLICY, UNKNOWN_PROVIDER,
    DUPLICATE_PROVIDER, UNKNOWN_REFERENCE, INVALID_REFERENCE, INVALID_QUANTITY, UNIT_MISMATCH,
    INVALID_TICK, INVALID_GRAPH, GRAPH_CYCLE, BUDGET_EXHAUSTED, PROVIDER_LIMIT_EXCEEDED,
    OBSERVATION_FAILED, NEED_DETECTION_FAILED, CONSTRAINT_DETECTION_FAILED,
    OPPORTUNITY_DISCOVERY_FAILED, CANDIDATE_GENERATION_FAILED, CANDIDATE_EVALUATION_FAILED,
    OPPORTUNITY_OVERALLOCATED, NEED_OVERCOVERED, UNSUPPORTED_ACTION, SUBMISSION_ADAPTER_MISSING,
    SUBMISSION_REJECTED, TARGET_PLAN_ALREADY_EXISTS, TARGET_PLAN_IDENTITY_CONFLICT,
    SCHEDULER_REJECTED, INVALID_STATUS, INVALID_STATUS_TRANSITION, TERMINAL_CYCLE,
    PERSISTENCE_FAILURE, UNSUPPORTED_SCHEMA, INTERNAL_INVARIANT_VIOLATION, UNKNOWN }
