package com.butchercraft.world.allocation;

public enum AllocationRuntimeFailureCode {
    NULL_VALUE,
    DUPLICATE_REGISTRATION,
    DUPLICATE_RUNTIME,
    DUPLICATE_COMMITMENT,
    UNKNOWN_REQUEST,
    UNKNOWN_SET,
    UNKNOWN_REQUIREMENT,
    UNKNOWN_COMMITMENT,
    UNKNOWN_REFERENCE,
    INVALID_TRANSITION,
    TERMINAL_RUNTIME,
    INVALID_SIMULATION_TICK,
    INVALID_TIMESTAMP,
    INVALID_STATUS_STATE,
    INVALID_COMMITMENT_ASSOCIATION,
    INCOMPLETE_COMMITMENT_SET,
    INVALID_REGISTRY_ORDERING,
    INVALID_SCHEMA_VERSION,
    INVALID_REPORT,
    INVALID_HISTORY,
    CAPACITY_UNAVAILABLE,
    SET_FAILED,
    SET_EXPIRED,
    ARITHMETIC_OVERFLOW,
    STRUCTURAL_VALIDATION_FAILED
}
