package com.butchercraft.world.allocation;

public enum AllocationValidationFailureCode {
    NULL_VALUE,
    MALFORMED_IDENTIFIER,
    INVALID_NAMESPACE,
    INVALID_SCHEMA_VERSION,
    INVALID_SIMULATION_TICK,
    ZERO_QUANTITY,
    NEGATIVE_QUANTITY,
    INCOMPATIBLE_UNIT,
    ARITHMETIC_OVERFLOW,
    QUANTITY_UNDERFLOW,
    INVALID_METADATA,
    INVALID_ORDERING_CONTEXT,
    EMPTY_REQUIREMENTS,
    EMPTY_ALLOCATION_SET,
    DUPLICATE_REQUIREMENT,
    DUPLICATE_RESOURCE,
    DUPLICATE_CAPACITY_KEY,
    DUPLICATE_OBSERVATION_REFERENCE,
    INCONSISTENT_EXECUTION_REFERENCE,
    INCONSISTENT_SET_ASSOCIATION,
    INCONSISTENT_REQUEST_ASSOCIATION,
    INVALID_EXPIRATION,
    NONCANONICAL_INPUT,
    UNSUPPORTED_SCHEMA_CONCEPT
}
