package com.butchercraft.world.allocation;

public enum AllocationProviderFailureCode {
    INVALID_PROVIDER_DESCRIPTOR,
    DUPLICATE_PROVIDER,
    REGISTRY_LIMIT_EXCEEDED,
    INVALID_REQUEST,
    INVALID_CONTEXT,
    TICK_MISMATCH,
    SCHEMA_MISMATCH,
    PROVIDER_ID_MISMATCH,
    INVALID_RESOURCE_SNAPSHOT,
    INVALID_CAPACITY_SNAPSHOT,
    DUPLICATE_RESOURCE,
    DUPLICATE_CAPACITY,
    CONFLICTING_OBSERVATION,
    UNAUTHORIZED_OWNER_REFERENCE,
    UNDECLARED_CAPABILITY,
    UNSUPPORTED_SCHEMA_CONCEPT,
    PROVIDER_EXCEPTION,
    RESULT_LIMIT_EXCEEDED,
    UNKNOWN_REFERENCE
}
