package com.butchercraft.world.allocation;

public enum AllocationCyclePhase {
    CAPTURE_EXPLICIT_INPUT,
    VALIDATE_CYCLE_ENVELOPE,
    VALIDATE_REFERENCES,
    OBSERVE_ACTIVE_COMMITMENTS,
    CONSTRUCT_WORKING_LEDGER,
    ORDER_ELIGIBLE_SETS,
    EVALUATE_ALLOCATION_SETS,
    CONSTRUCT_COMMITMENTS,
    VALIDATE_PROPOSED_RESULT,
    PUBLISH_ATOMICALLY,
    PRODUCE_IMMUTABLE_EVIDENCE
}
