package com.butchercraft.workstation.endpoint;

public enum WorkstationEndpointResultCode {
    APPLIED,
    DUPLICATE_OBSERVED,
    ENDPOINT_NOT_ACTIVE,
    ENDPOINT_UNAVAILABLE,
    ENDPOINT_IDENTITY_CONFLICT,
    INVENTORY_FRESHNESS_CONFLICT,
    SOURCE_EMPTY,
    INVALID_QUANTITY,
    INSUFFICIENT_SOURCE_QUANTITY,
    UNSUPPORTED_SOURCE_COUNT,
    SOURCE_MISMATCH,
    DESTINATION_OCCUPIED,
    DESTINATION_CAPACITY_EXCEEDED,
    INCOMPATIBLE_STACK,
    DESTINATION_REJECTED,
    CONFIGURATION_MISMATCH,
    MIGRATION_BLOCKED,
    UNSUPPORTED_SCHEMA,
    UNSUPPORTED_EFFECT,
    RECOVERY_REQUIRED,
    UNKNOWN_OUTCOME
}
