package com.butchercraft.workstation.endpoint;

public enum WorkstationEndpointResultCode {
    APPLIED,
    DUPLICATE_OBSERVED,
    ENDPOINT_NOT_ACTIVE,
    ENDPOINT_UNAVAILABLE,
    ENDPOINT_IDENTITY_CONFLICT,
    INVENTORY_FRESHNESS_CONFLICT,
    SOURCE_EMPTY,
    SOURCE_MISMATCH,
    DESTINATION_OCCUPIED,
    DESTINATION_REJECTED,
    UNSUPPORTED_EFFECT,
    RECOVERY_REQUIRED,
    UNKNOWN_OUTCOME
}
