package com.butchercraft.world.transaction;

public enum TransactionFailureCode {
    UNKNOWN_GOOD,
    UNKNOWN_INVENTORY,
    UNKNOWN_ACTOR,
    NEGATIVE_QUANTITY,
    INSUFFICIENT_INVENTORY,
    CAPACITY_EXCEEDED,
    INVALID_STATUS,
    PROPOSAL_IDENTITY_MISMATCH,
    INVENTORY_FRESHNESS_MISMATCH,
    VALIDATION_PLAN_MISMATCH,
    MISSING_VALIDATION_BINDING,
    VALIDATION_AUTHORITY_UNAVAILABLE,
    VALIDATION_AUTHORITY_CONSUMED,
    TRANSACTION_IDENTITY_CONFLICT,
    RESULT_EVIDENCE_MISMATCH,
    UNSUPPORTED_BINDING_SCHEMA,
    APPLICATION_WITHOUT_VALIDATION,
    PERSISTENCE_COMPATIBILITY_FAILURE,
    VALIDATION_FAILED,
    UNKNOWN
}
